enable update scripts to update requirements
- Also pin requirements to known working commits.
- This may be a breaking change; exercise with caution
- No functional testing performed yet!

diff --git a/simple_install/templates/update.sh.in b/simple_install/templates/update.sh.in
--- a/simple_install/templates/update.sh.in
+++ b/simple_install/templates/update.sh.in
@@ -3,14 +3,36 @@
 set -eu
 
 INVOKE_AI_SRC=https://github.com/invoke-ai/InvokeAI/archive/main.zip
-
 # ensure we're in the correct folder in case user's CWD is somewhere else
 scriptdir=$(dirname "$0")
 cd "$scriptdir"
 
+function _err_exit {
+    if test "$1" -ne 0
+    then
+	echo "Something went wrong while installing InvokeAI and/or its requirements."
+	echo "Update cannot continue. Please report this error to https://github.com/invoke-ai/InvokeAI/issues"
+        echo -e "Error code $1; Error caught was '$2'"
+        read -p "Press any key to exit..."
+        exit
+    fi
+}
+
+echo This script will update InvokeAI and all its dependencies. If you do not want to do this, press control-C now!
+read -p "Press any key to continue, or CTRL-C to exit..."
+
 . .venv/bin/activate
 
+pip install -r requirements.txt
+_err_exit $? "The pip program failed to install InvokeAI's requirements."
+
 pip install $INVOKE_AI_SRC
+_err_exit $? "The pip program failed to install InvokeAI."
+
+python .venv/bin/configure_invoke.py
+_err_exit $? "The configure script failed to run successfully."
+
+
 
 
 
